### ISSUE TITLE
Shape Data

### ISSUE THREAD

**Issue by geisi93** [whosonfirst-data/whosonfirst-data-postalcode-at#4]
Hi,

do you still have the shape data for austria's zip codes? Unfortunately, they are no longer retrievable at https://www.data.gv.at/katalog/dataset/c33d36b0-f184-4f2a-89cc-839ca7fcf88a (as linked in #1)

Thanks in advance

**Comment by thisisaaronland** [comment]
All of the data for each postal code is encoded as individual GeoJSON files in the [data directory](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-at/tree/master/data).
